import { Registry } from "@/registry/schema";

export const demos: Registry = [
  {
    name: "basic-usage",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/basic-usage.tsx"],
  },
  {
    name: "header-clip",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/header-clip.tsx"],
  },
  {
    name: "content-inset-sidebar",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/content-inset-sidebar.tsx"],
  },
  {
    name: "footer-avoiding-view",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/footer-avoiding-view.tsx"],
  },
  {
    name: "edgeSidebar-visibility",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/edgeSidebar-visibility.tsx"],
  },
  {
    name: "edgeSidebar-collapse",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/edgeSidebar-collapse.tsx"],
  },
  {
    name: "edgeSidebar-hoverUncollapse",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/edgeSidebar-hoverUncollapse.tsx"],
  },
  {
    name: "edgeSidebar-drawer",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/edgeSidebar-drawer.tsx"],
  },
  {
    name: "edgeSidebar-drawer-withoutOverlay",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/edgeSidebar-drawer-withoutOverlay.tsx"],
  },
  {
    name: "edgeSidebar-responsive",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/edgeSidebar-responsive.tsx"],
  },
  {
    name: "edgeSidebar-right",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/edgeSidebar-right.tsx"],
  },
  {
    name: "insetSidebar-width",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/insetSidebar-width.tsx"],
  },
  {
    name: "insetSidebar-absolute",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/insetSidebar-absolute.tsx"],
  },
  {
    name: "sidebar-menus",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-menus.tsx"],
  },
  {
    name: "sidebar-menu-groups",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-menu-groups.tsx"],
  },
  {
    name: "sidebar-menu-action",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-menu-action.tsx"],
  },
  {
    name: "sidebar-menu-tooltip",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-menu-tooltip.tsx"],
  },
  {
    name: "sidebar-menu-groupText",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-menu-groupText.tsx"],
  },
  {
    name: "sidebar-elements",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-elements.tsx"],
  },
  {
    name: "sidebar-menu-nested",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-menu-nested.tsx"],
  },
  {
    name: "sidebar-menu-collapsible",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/sidebar-menu-collapsible.tsx"],
  },
  {
    name: "standard-dock",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/standard-dock.tsx"],
  },
  {
    name: "dock-example1",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-example1.tsx"],
  },
  {
    name: "dock-float",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-float.tsx"],
  },
  {
    name: "dock-horizontal-menu",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-horizontal-menu.tsx"],
  },
  {
    name: "dock-icon-only",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-icon-only.tsx"],
  },
  {
    name: "dock-indicator",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-indicator.tsx"],
  },
  {
    name: "dock-tooltip-hasIndicator",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-tooltip-hasIndicator.tsx"],
  },
  {
    name: "dock-tooltip-noIndicator",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-tooltip-noIndicator.tsx"],
  },
  {
    name: "dock-tooltip",
    type: "registry:ui",
    dependencies: [],
    files: ["demo/dock-tooltip.tsx"],
  },
];
