// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "basic-usage": {
      name: "basic-usage",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/basic-usage.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/basic-usage.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "header-clip": {
      name: "header-clip",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/header-clip.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/header-clip.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "content-inset-sidebar": {
      name: "content-inset-sidebar",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/content-inset-sidebar.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/content-inset-sidebar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "footer-avoiding-view": {
      name: "footer-avoiding-view",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/footer-avoiding-view.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/footer-avoiding-view.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-visibility": {
      name: "edgeSidebar-visibility",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-visibility.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-visibility.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-collapse": {
      name: "edgeSidebar-collapse",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-collapse.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-collapse.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-hoverExpand": {
      name: "edgeSidebar-hoverExpand",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-hoverExpand.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-hoverExpand.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-drawer": {
      name: "edgeSidebar-drawer",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-drawer.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-drawer.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-drawer-withoutOverlay": {
      name: "edgeSidebar-drawer-withoutOverlay",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-drawer-withoutOverlay.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-drawer-withoutOverlay.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-responsive": {
      name: "edgeSidebar-responsive",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-responsive.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-responsive.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-right": {
      name: "edgeSidebar-right",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-right.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-right.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "insetSidebar-width": {
      name: "insetSidebar-width",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/insetSidebar-width.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/insetSidebar-width.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "insetSidebar-absolute": {
      name: "insetSidebar-absolute",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/insetSidebar-absolute.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/insetSidebar-absolute.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
