// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "basic-usage": {
      name: "basic-usage",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/basic-usage.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/basic-usage.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "header-clip": {
      name: "header-clip",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/header-clip.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/header-clip.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "content-inset-sidebar": {
      name: "content-inset-sidebar",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/content-inset-sidebar.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/content-inset-sidebar.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "footer-avoiding-view": {
      name: "footer-avoiding-view",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/footer-avoiding-view.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/footer-avoiding-view.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-visibility": {
      name: "edgeSidebar-visibility",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-visibility.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-visibility.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-collapse": {
      name: "edgeSidebar-collapse",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-collapse.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-collapse.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-hoverUncollapse": {
      name: "edgeSidebar-hoverUncollapse",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-hoverUncollapse.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-hoverUncollapse.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-drawer": {
      name: "edgeSidebar-drawer",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-drawer.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-drawer.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-drawer-withoutOverlay": {
      name: "edgeSidebar-drawer-withoutOverlay",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-drawer-withoutOverlay.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-drawer-withoutOverlay.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-responsive": {
      name: "edgeSidebar-responsive",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-responsive.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-responsive.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "edgeSidebar-right": {
      name: "edgeSidebar-right",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/edgeSidebar-right.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/edgeSidebar-right.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "insetSidebar-width": {
      name: "insetSidebar-width",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/insetSidebar-width.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/insetSidebar-width.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "insetSidebar-absolute": {
      name: "insetSidebar-absolute",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/insetSidebar-absolute.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/insetSidebar-absolute.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-menus": {
      name: "sidebar-menus",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-menus.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-menus.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-menu-groups": {
      name: "sidebar-menu-groups",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-menu-groups.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-menu-groups.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-menu-action": {
      name: "sidebar-menu-action",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-menu-action.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-menu-action.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-menu-tooltip": {
      name: "sidebar-menu-tooltip",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-menu-tooltip.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-menu-tooltip.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-menu-groupText": {
      name: "sidebar-menu-groupText",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-menu-groupText.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-menu-groupText.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-elements": {
      name: "sidebar-elements",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-elements.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-elements.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-menu-nested": {
      name: "sidebar-menu-nested",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-menu-nested.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-menu-nested.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sidebar-menu-collapsible": {
      name: "sidebar-menu-collapsible",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/sidebar-menu-collapsible.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/sidebar-menu-collapsible.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "standard-dock": {
      name: "standard-dock",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/standard-dock.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/standard-dock.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-example1": {
      name: "dock-example1",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-example1.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-example1.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-float": {
      name: "dock-float",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-float.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-float.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-horizontal-menu": {
      name: "dock-horizontal-menu",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-horizontal-menu.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-horizontal-menu.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-icon-only": {
      name: "dock-icon-only",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-icon-only.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-icon-only.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-indicator": {
      name: "dock-indicator",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-indicator.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-indicator.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-tooltip-hasIndicator": {
      name: "dock-tooltip-hasIndicator",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-tooltip-hasIndicator.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-tooltip-hasIndicator.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-tooltip-noIndicator": {
      name: "dock-tooltip-noIndicator",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-tooltip-noIndicator.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-tooltip-noIndicator.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dock-tooltip": {
      name: "dock-tooltip",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/dock-tooltip.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/dock-tooltip.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "examples-flat-menus": {
      name: "examples-flat-menus",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/examples-flat-menus.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/examples-flat-menus.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "examples-group-menus": {
      name: "examples-group-menus",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/examples-group-menus.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/examples-group-menus.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "examples-collapsible-menus": {
      name: "examples-collapsible-menus",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/examples-collapsible-menus.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/examples-collapsible-menus.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "examples-collapsible-menus-secondary-action": {
      name: "examples-collapsible-menus-secondary-action",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/demo/examples-collapsible-menus-secondary-action.tsx"],
      component: React.lazy(() => import("@/registry/default/demo/examples-collapsible-menus-secondary-action.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
